# Generated by Django 4.2.16 on 2024-11-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='date',
            new_name='slot_date',
        ),
    ]
