# Generated by Django 4.2.16 on 2024-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_timeslot_slot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='slot_date',
            new_name='date',
        ),
    ]
